import { useState } from 'react';
import Link from 'next/link';
import Head from 'next/head';
import { format, parseISO } from 'date-fns';
import DatePicker from 'react-datepicker';
import 'react-datepicker/dist/react-datepicker.css';
import Header from '../../components/Header';
import fakeTasks from '../../services/fakeTaskService';
import Button from '../../components/Button';

export const getStaticPaths = async () => {
  const data = await new Promise((res, rej) => {
    setTimeout(() => {
      res(fakeTasks);
    });
  }, 500);

  const paths = data.map((task) => {
    return {
      params: { id: task._id },
    };
  });

  return {
    paths,
    fallback: false,
  };
};

export const getStaticProps = async (context) => {
  const id = context.params.id;
  const details = await new Promise((res, rej) => {
    setTimeout(() => {
      const result = fakeTasks.find((task) => task._id === id);
      res(result);
    }, 500);
  });

  return {
    props: { details },
  };
};

const TaskDetails = ({ details }) => {
  const [title, setTitle] = useState(details.title);
  const [description, setDescription] = useState(details.description);
  const [dueDate, setDueDate] = useState(parseISO(details.dueDate));

  const overdue = details.dueDate < new Date().toISOString();

  return (
    <div className="container">
      <Head>
        <title>To-do List App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div className="card">
        <div className="task-form">
          <Link href="/">
            <a>Back to task list...</a>
          </Link>
          <input
            type="text"
            className="task-form-title"
            onChange={(e) => setTitle(e.target.value)}
            value={title}
            required
          />
          <div
            className={`task-form-status ${
              details.isComplete
                ? 'task-form-status-complete'
                : !details.isComplete && !overdue
                ? 'task-form-status-incomplete'
                : !details.isComplete && overdue
                ? 'task-form-status-overdue'
                : ''
            }`}
          >
            <p>
              {details.isComplete && !overdue
                ? 'Complete'
                : !details.isComplete && !overdue
                ? 'Incomplete'
                : !details.isComplete && overdue
                ? 'Overdue'
                : ''}
            </p>
          </div>
          <div className="task-form-due-date">
            <p>Due date:</p>
            <DatePicker
              className="task-form-due-date-picker"
              selected={dueDate}
              onChange={(date) => setDueDate(date)}
            />
            {overdue && <p>Overdue</p>}
          </div>
          <textarea
            className="task-form-description"
            cols="85"
            rows="3"
            placeholder="task description..."
            onChange={(e) => setDescription(e.target.value)}
            value={description}
          ></textarea>
          <div className="form-div">
            <Button className="default-btn light-primary-btn" type="submit">
              Save Task
            </Button>
          </div>
        </div>
      </div>
    </div>
  );
};

export default TaskDetails;
