import { useState } from 'react';
import Head from 'next/head';
import Loader from '../components/Loader';
import Header from '../components/Header';
import TaskListForm from '../components/TaskListForm';
import fakeTasks from '../services/fakeTaskService';
import TaskTable from '../components/TaskTable';

export default function Home() {
  const [tasks, setTasks] = useState(fakeTasks);
  const [loading, setLoading] = useState(false);
  const [filterType, setFilterType] = useState('all');

  const handleAddTask = (task) => {
    const tasksCopy = [...tasks];
    setTasks([...tasksCopy, task]);
  };

  const handleTaskDelete = (id) => {
    const filteredTasks = tasks.filter((t) => t._id !== id);
    setTasks(filteredTasks);
  };

  const handleTaskCompleteToggle = (task) => {
    const tasksCopy = [...tasks];
    const index = tasksCopy.indexOf(task);
    tasksCopy[index] = { ...task, isComplete: !task.isComplete };
    setTasks(tasksCopy);
  };

  const handleCompletedTaskDelete = () => {
    const filteredTasks = tasks.filter((t) => t.isComplete === false);
    setTasks(filteredTasks);
  };

  const handleChangeFilterType = (filterType) => {
    setFilterType(filterType);
  };

  const filteredTasks = tasks.filter((task) => {
    if (filterType === 'all') {
      return tasks;
    }
    if (filterType === 'complete') {
      return task.isComplete === true;
    }
    if (filterType === 'overdue') {
      return !task.isComplete && task.dueDate < new Date().toISOString();
    }
  });

  return (
    <div className="container">
      <Head>
        <title>To-do List App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <TaskListForm onAddTask={handleAddTask} />
      <TaskTable
        tasks={filteredTasks}
        onTaskDelete={handleTaskDelete}
        onTaskCompleteToggle={handleTaskCompleteToggle}
        onChangeFilterType={handleChangeFilterType}
        onCompletedTaskDelete={handleCompletedTaskDelete}
      />
    </div>
  );
}
